apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roach-bank-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-server
            port:
              name: http